"""Initial database setup

Revision ID: 0589425f3de6
Revises: 1b52706956be
Create Date: 2025-06-07 11:44:57.141602

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '0589425f3de6'
down_revision: str | None = '1b52706956be'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
